### ISSUE TITLE
ModuleNotFoundError: No module named 'config_parser'

### ISSUE THREAD

**Issue by wuhaoran111** [Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting#2]
When i try to run the preprocess for Home with 
`
python3 common_data_processing/script_vectorize_hd_maps.py --cfg configs/home.yaml
`
I got this error:
```
Traceback (most recent call last):
  File "common_data_processing/script_vectorize_hd_maps.py", line 16, in <module>
    import config_parser
ModuleNotFoundError: No module named 'config_parser'
```
Do you have any idea with it?

**Comment by wuhaoran111** [comment]
I have solved it by adding src to PYTHONPATH, and i find that using n_process=1 for home is also quicker.

**Comment by Robotmurlock** [comment]
Hey @wuhaoran111. Glad you managed to figure it out. Using single process for full pipeline is probably okay.
