### ISSUE TITLE
Tensorboard Log

### ISSUE THREAD

**Issue by 9p15p** [Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting#6]
Thanks for your great work.
Can you please share the Tensorboard log files?

**Comment by Robotmurlock** [comment]
Hey, sorry for slow response. I will clean and upload Tensorboard logs to Google drive soon.

**Comment by THN0000** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Robotmurlock** [comment]
I uploaded tensorboard on google drive. Check model zoo.
