### ISSUE TITLE
Could you please share your code.

### ISSUE THREAD

**Issue by flyzenr** [Robotmurlock/TNT-VectorNet-and-HOME-Trajectory-Forecasting#7]
Could you please share your code. 

My email is 11930923@mail.sustech.edu.cn. 

Thanks!

**Comment by THN0000** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
